server:
  ip: 111.192.158.189
  port: 80
logging:
  config: classpath:logback.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.245.9:3306/dev_webapp?useUnicode=true&characterEncoding=utf8
    username: root
    password: '!QAZ2wsx'
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    type: com.alibaba.druid.pool.DruidDataSource
